//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.Kinect.BodyBasics
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_exam
    {

        public const String ExamFinishFlagStart = "S";
        public const String ExamFinishFlagEnd = "E";

        public const String AnalysisEnd = "E";
        public tab_exam()
        {
            this.tab_exam_record = new HashSet<tab_exam_record>();
        }
    
        public int person_id { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> exam_date { get; set; }
        public string operater { get; set; }
        public Nullable<int> exam_age { get; set; }
        public string finish_flag { get; set; }
        public string analysis_flag { get; set; }
    
        public virtual tab_person tab_person { get; set; }
        public virtual ICollection<tab_exam_record> tab_exam_record { get; set; }
    }
}
