//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.Kinect.BodyBasics
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_person
    {
        public tab_person()
        {
            this.tab_exam = new HashSet<tab_exam>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string race { get; set; }
        public Nullable<float> height { get; set; }
        public Nullable<float> weight { get; set; }
    
        public virtual ICollection<tab_exam> tab_exam { get; set; }
    }
}
