//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.Kinect.BodyBasics
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_exam_type
    {
        public tab_exam_type()
        {
            this.tab_exam_record = new HashSet<tab_exam_record>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public int order { get; set; }
        public int style { get; set; }
    
        public virtual ICollection<tab_exam_record> tab_exam_record { get; set; }
    }
}
