//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.Kinect.BodyBasics
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_exam_record
    {
        public int id { get; set; }
        public int exam_type_id { get; set; }
        public int exam_id { get; set; }
        public Nullable<double> SpineBaseX { get; set; }
        public Nullable<double> SpineBaseY { get; set; }
        public Nullable<double> SpineBaseZ { get; set; }
        public Nullable<double> SpineMidX { get; set; }
        public Nullable<double> SpineMidY { get; set; }
        public Nullable<double> SpineMidZ { get; set; }
        public Nullable<double> NeckX { get; set; }
        public Nullable<double> NeckY { get; set; }
        public Nullable<double> NeckZ { get; set; }
        public Nullable<double> HeadX { get; set; }
        public Nullable<double> HeadY { get; set; }
        public Nullable<double> HeadZ { get; set; }
        public Nullable<double> SpineShoulderX { get; set; }
        public Nullable<double> SpineShoulderY { get; set; }
        public Nullable<double> SpineShoulderZ { get; set; }
        public Nullable<double> ShoulderLeftX { get; set; }
        public Nullable<double> ShoulderLeftY { get; set; }
        public Nullable<double> ShoulderLeftZ { get; set; }
        public Nullable<double> ElbowLeftX { get; set; }
        public Nullable<double> ElbowLeftY { get; set; }
        public Nullable<double> ElbowLeftZ { get; set; }
        public Nullable<double> WristLeftX { get; set; }
        public Nullable<double> WristLeftY { get; set; }
        public Nullable<double> WristLeftZ { get; set; }
        public Nullable<double> HandLeftX { get; set; }
        public Nullable<double> HandLeftY { get; set; }
        public Nullable<double> HandLeftZ { get; set; }
        public Nullable<double> HipLeftX { get; set; }
        public Nullable<double> HipLeftY { get; set; }
        public Nullable<double> HipLeftZ { get; set; }
        public Nullable<double> KneeLeftX { get; set; }
        public Nullable<double> KneeLeftY { get; set; }
        public Nullable<double> KneeLeftZ { get; set; }
        public Nullable<double> AnkleLeftX { get; set; }
        public Nullable<double> AnkleLeftY { get; set; }
        public Nullable<double> AnkleLeftZ { get; set; }
        public Nullable<double> FootLeftX { get; set; }
        public Nullable<double> FootLeftY { get; set; }
        public Nullable<double> FootLeftZ { get; set; }
        public Nullable<double> HandTipLeftX { get; set; }
        public Nullable<double> HandTipLeftY { get; set; }
        public Nullable<double> HandTipLeftZ { get; set; }
        public Nullable<double> ThumbLeftX { get; set; }
        public Nullable<double> ThumbLeftY { get; set; }
        public Nullable<double> ThumbLeftZ { get; set; }
        public Nullable<double> ShoulderRightX { get; set; }
        public Nullable<double> ShoulderRightY { get; set; }
        public Nullable<double> ShoulderRightZ { get; set; }
        public Nullable<double> ElbowRightX { get; set; }
        public Nullable<double> ElbowRightY { get; set; }
        public Nullable<double> ElbowRightZ { get; set; }
        public Nullable<double> WristRightX { get; set; }
        public Nullable<double> WristRightY { get; set; }
        public Nullable<double> WristRightZ { get; set; }
        public Nullable<double> HandRightX { get; set; }
        public Nullable<double> HandRightY { get; set; }
        public Nullable<double> HandRightZ { get; set; }
        public Nullable<double> HipRightX { get; set; }
        public Nullable<double> HipRightY { get; set; }
        public Nullable<double> HipRightZ { get; set; }
        public Nullable<double> KneeRightX { get; set; }
        public Nullable<double> KneeRightY { get; set; }
        public Nullable<double> KneeRightZ { get; set; }
        public Nullable<double> AnkleRightX { get; set; }
        public Nullable<double> AnkleRightY { get; set; }
        public Nullable<double> AnkleRightZ { get; set; }
        public Nullable<double> FootRightX { get; set; }
        public Nullable<double> FootRightY { get; set; }
        public Nullable<double> FootRightZ { get; set; }
        public Nullable<double> HandTipRightX { get; set; }
        public Nullable<double> HandTipRightY { get; set; }
        public Nullable<double> HandTipRightZ { get; set; }
        public Nullable<double> ThumbRightX { get; set; }
        public Nullable<double> ThumbRightY { get; set; }
        public Nullable<double> ThumbRightZ { get; set; }
        public Nullable<System.DateTime> exam_time { get; set; }
        public string exam_snapshot_path { get; set; }
    
        public virtual tab_exam tab_exam { get; set; }
        public virtual tab_exam_type tab_exam_type { get; set; }
    }
}
